name: Hello Word Integração Contínua!

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  OlaMundo: 
    runs-on: ubunto-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Diga
        run: echo Heloo-world!
